import {
  AutomationFlow,
  Campaign,
  Contact,
  Conversation,
  Message,
  RevenueAnalytics,
  Template,
  User,
  WhatsappStatus,
} from './types';

export const mockUser: User = {
  id: 'usr_1',
  name: 'Kamlesh Sharma',
  email: 'admin@company.com',
  role: 'ADMIN',
};

export const mockWabaStatus: WhatsappStatus = {
  connected: true,
  wabaId: '109845728392019',
  phoneNumberId: '104829104829104',
  displayPhoneNumber: '+1 (555) 019-2834',
  tier: 'TIER_10K',
  qualityRating: 'GREEN',
  connectedAt: new Date(Date.now() - 45 * 86400000).toISOString(),
  dailyMessageLimit: 10000,
  dailyMessagesSent: 4210,
  spamReportRate: 0.03, // 0.03% (Threshold < 0.10%)
  blockRate: 0.08,      // 0.08% (Threshold < 0.20%)
  freeMonthlyServiceUsed: 420, // 420 / 1000 free service convs used
};

export const mockRegionalPricing = [
  { country: 'United States & Canada', code: 'US', marketingRate: 0.025, utilityRate: 0.015, serviceRate: 0.008, authRate: 0.013 },
  { country: 'India', code: 'IN', marketingRate: 0.0094, utilityRate: 0.0042, serviceRate: 0.0035, authRate: 0.0028 },
  { country: 'United Kingdom', code: 'GB', marketingRate: 0.042, utilityRate: 0.022, serviceRate: 0.012, authRate: 0.020 },
  { country: 'European Union (Avg)', code: 'EU', marketingRate: 0.055, utilityRate: 0.028, serviceRate: 0.015, authRate: 0.025 },
  { country: 'Brazil / Latin America', code: 'BR', marketingRate: 0.062, utilityRate: 0.035, serviceRate: 0.018, authRate: 0.030 },
];

export const mockAnalytics7d: RevenueAnalytics = {
  timeframe: '7d',
  totalRevenue: 28450,
  revenueGrowth: 24.8,
  totalSpend: 1420,
  roiMultiplier: 20.0,
  averageOrderValue: 142.5,
  totalConversations: 8940,
  marketingCost: 1180,
  utilityCost: 190,
  serviceCost: 50,
  freeServiceUsed: 420,
  cacValue: 11.8,
  ltvValue: 242.0,
  funnel: {
    sent: 14250,
    delivered: 14020, // 98.4%
    read: 12280,      // 86.2%
    engaged: 4090,    // 28.7%
    converted: 1200,  // 8.4%
  },
  dailyTrend: [
    { date: 'Mon', revenue: 3400, cost: 180, messages: 1850, conversions: 145 },
    { date: 'Tue', revenue: 4100, cost: 210, messages: 2100, conversions: 178 },
    { date: 'Wed', revenue: 3850, cost: 195, messages: 1980, conversions: 162 },
    { date: 'Thu', revenue: 4900, cost: 240, messages: 2450, conversions: 210 },
    { date: 'Fri', revenue: 5200, cost: 260, messages: 2680, conversions: 228 },
    { date: 'Sat', revenue: 3900, cost: 190, messages: 1940, conversions: 160 },
    { date: 'Sun', revenue: 3100, cost: 145, messages: 1250, conversions: 117 },
  ],
  regionalPricing: mockRegionalPricing,
  channelComparison: {
    whatsapp: { openRate: 86.2, ctr: 28.7, conversionRate: 8.4, roi: 20.0 },
    sms: { openRate: 42.1, ctr: 8.3, conversionRate: 2.1, roi: 4.8 },
    email: { openRate: 21.5, ctr: 3.2, conversionRate: 1.2, roi: 3.2 },
  },
};

export const mockAnalytics30d: RevenueAnalytics = {
  timeframe: '30d',
  totalRevenue: 118600,
  revenueGrowth: 31.4,
  totalSpend: 5920,
  roiMultiplier: 20.0,
  averageOrderValue: 145.0,
  totalConversations: 38400,
  marketingCost: 4950,
  utilityCost: 780,
  serviceCost: 190,
  freeServiceUsed: 890,
  cacValue: 12.0,
  ltvValue: 248.0,
  funnel: {
    sent: 58900,
    delivered: 57950,
    read: 50800,
    engaged: 16900,
    converted: 4950,
  },
  dailyTrend: [
    { date: 'Week 1', revenue: 26500, cost: 1350, messages: 13500, conversions: 1100 },
    { date: 'Week 2', revenue: 29800, cost: 1490, messages: 14800, conversions: 1240 },
    { date: 'Week 3', revenue: 32400, cost: 1620, messages: 16100, conversions: 1360 },
    { date: 'Week 4', revenue: 29900, cost: 1460, messages: 14500, conversions: 1250 },
  ],
  regionalPricing: mockRegionalPricing,
  channelComparison: {
    whatsapp: { openRate: 86.2, ctr: 28.7, conversionRate: 8.4, roi: 20.0 },
    sms: { openRate: 42.1, ctr: 8.3, conversionRate: 2.1, roi: 4.8 },
    email: { openRate: 21.5, ctr: 3.2, conversionRate: 1.2, roi: 3.2 },
  },
};

export const mockAutomations: AutomationFlow[] = [
  {
    id: 'flw_1',
    name: 'High-Intent Cart Abandonment Drip',
    triggerEvent: 'Checkout Abandoned > $100',
    status: 'ACTIVE',
    stats: {
      triggered: 1420,
      delivered: 1395,
      converted: 318,
      revenue: 46110,
    },
    steps: [
      { id: 's1', type: 'TRIGGER', title: 'Webhook Trigger', description: 'User adds items to cart & exits checkout' },
      { id: 's2', type: 'DELAY', title: 'Smart Delay (45 mins)', description: 'Wait 45 minutes for organic checkout' },
      { id: 's3', type: 'SEND_TEMPLATE', title: 'Send Template: abandoned_cart_recovery', description: 'Deliver personalized cart image + Free Express Shipping link' },
      { id: 's4', type: 'CONDITION', title: 'Check Purchase Status (24 hrs)', description: 'IF purchased -> Tag VIP, ELSE -> Win-back offer 10% off' },
    ],
  },
  {
    id: 'flw_2',
    name: 'Order Fulfillment & Live Tracking',
    triggerEvent: 'Order Dispatched',
    status: 'ACTIVE',
    stats: {
      triggered: 3840,
      delivered: 3810,
      converted: 480,
      revenue: 12400,
    },
    steps: [
      { id: 's2_1', type: 'TRIGGER', title: 'Fulfillment Webhook', description: 'Courier scans tracking package' },
      { id: 's2_2', type: 'SEND_TEMPLATE', title: 'Send Template: order_status_dispatched', description: 'Live tracking link & 24/7 care support button' },
    ],
  },
  {
    id: 'flw_3',
    name: 'Post-Delivery NPS & Review Collector',
    triggerEvent: 'Package Delivered + 48h',
    status: 'ACTIVE',
    stats: {
      triggered: 2100,
      delivered: 2080,
      converted: 940,
      revenue: 0,
    },
    steps: [
      { id: 's3_1', type: 'TRIGGER', title: 'Delivery Confirmed Webhook', description: 'Package marked delivered' },
      { id: 's3_2', type: 'DELAY', title: 'Experience Delay (48 hrs)', description: 'Give customer 2 days to experience product' },
      { id: 's3_3', type: 'SEND_TEMPLATE', title: 'Interactive NPS Score Survey', description: 'Quick reply buttons (⭐⭐⭐⭐⭐) to collect review on Google/Trustpilot' },
    ],
  },
];

export const mockTemplates: Template[] = [
  {
    id: 'tpl_1',
    name: 'summer_flash_sale_vip',
    language: 'en_US',
    category: 'MARKETING',
    status: 'APPROVED',
    metaTemplateId: 'meta_938102948',
    bodyJson: {
      header: { type: 'TEXT', text: '⚡ Exclusive Summer Flash Sale!' },
      body: 'Hi {{1}}, your exclusive 25% VIP discount on all new arrivals is live for the next 24 hours only. Use code {{2}} at checkout.',
      footer: 'Reply STOP to opt out',
      buttons: [
        { type: 'URL', text: 'Shop Now', url: 'https://store.example.com/summer-sale' },
        { type: 'QUICK_REPLY', text: 'View Catalog' },
      ],
    },
    sampleVariables: { '1': 'Elena', '2': 'VIP25' },
    createdAt: '2026-08-20T10:00:00Z',
  },
  {
    id: 'tpl_2',
    name: 'order_status_dispatched',
    language: 'en_US',
    category: 'UTILITY',
    status: 'APPROVED',
    metaTemplateId: 'meta_184920491',
    bodyJson: {
      header: { type: 'TEXT', text: '📦 Order #{{1}} is on its way!' },
      body: 'Hello {{2}}, your order has been packed and handed over to {{3}}. Estimated delivery date: {{4}}.',
      footer: 'Customer Support: 24/7',
      buttons: [
        { type: 'URL', text: 'Track Shipment', url: 'https://tracking.example.com/order/{{1}}' },
        { type: 'QUICK_REPLY', text: 'Need Help?' },
      ],
    },
    sampleVariables: { '1': 'ORD-8921', '2': 'Marcus', '3': 'FedEx Express', '4': 'Friday, Sept 12' },
    createdAt: '2026-08-15T14:30:00Z',
  },
  {
    id: 'tpl_3',
    name: 'abandoned_cart_recovery',
    language: 'en_US',
    category: 'MARKETING',
    status: 'APPROVED',
    metaTemplateId: 'meta_749201948',
    bodyJson: {
      header: { type: 'IMAGE', url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600' },
      body: 'Hi {{1}}, you left some favorite items in your cart! Complete your checkout now and get Free Express Shipping.',
      footer: 'Valid for 12 hours',
      buttons: [
        { type: 'URL', text: 'Resume Checkout', url: 'https://store.example.com/cart?recover={{2}}' },
      ],
    },
    sampleVariables: { '1': 'Sophia', '2': 'CRT9048' },
    createdAt: '2026-08-28T09:15:00Z',
  },
  {
    id: 'tpl_4',
    name: 'otp_verification_code',
    language: 'en_US',
    category: 'AUTHENTICATION',
    status: 'APPROVED',
    metaTemplateId: 'meta_391029482',
    bodyJson: {
      body: 'Your verification code is {{1}}. Valid for 10 minutes. Do not share this code with anyone.',
      footer: 'WhatsApp Security',
      buttons: [
        { type: 'QUICK_REPLY', text: 'Copy Code' },
      ],
    },
    sampleVariables: { '1': '948201' },
    createdAt: '2026-08-10T12:00:00Z',
  },
  {
    id: 'tpl_5',
    name: 'weekly_special_deal_utility_test',
    language: 'en_US',
    category: 'UTILITY',
    status: 'PENDING',
    metaTemplateId: null,
    bodyJson: {
      header: { type: 'TEXT', text: 'Notice: Special weekly deal update' },
      body: 'Check out our 50% discount offer on all products today only!',
      footer: 'Offer valid till stock lasts',
    },
    sampleVariables: {},
    createdAt: '2026-09-08T16:20:00Z',
    warning: 'Tagged Utility but contains "discount", "offer" — Meta may re-categorize this as Marketing and bill accordingly (§02).',
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 'cmp_1',
    name: 'September VIP Flash Sale',
    templateId: 'tpl_1',
    templateName: 'summer_flash_sale_vip',
    category: 'MARKETING',
    status: 'COMPLETED',
    sentAt: '2026-09-06T11:00:00Z',
    targetTags: ['VIP Customers', 'High LTV'],
    totalRecipients: 4200,
    stats: {
      sent: 4200,
      delivered: 4140,
      read: 3780,
      clickedOrReplied: 1420,
      converted: 432,
      failed: 60,
      revenue: 18450,
      cost: 380,
    },
  },
  {
    id: 'cmp_2',
    name: 'Abandoned Cart Auto-Recovery (Weekly)',
    templateId: 'tpl_3',
    templateName: 'abandoned_cart_recovery',
    category: 'MARKETING',
    status: 'SENDING',
    sentAt: '2026-09-09T08:30:00Z',
    targetTags: ['Cart Abandoners'],
    totalRecipients: 1850,
    stats: {
      sent: 1850,
      delivered: 1820,
      read: 1590,
      clickedOrReplied: 620,
      converted: 195,
      failed: 30,
      revenue: 8900,
      cost: 165,
    },
  },
  {
    id: 'cmp_3',
    name: 'Festive Season Early Birds Preview',
    templateId: 'tpl_1',
    templateName: 'summer_flash_sale_vip',
    category: 'MARKETING',
    status: 'SCHEDULED',
    scheduledAt: '2026-09-15T10:00:00Z',
    targetTags: ['Newsletter Subscribers', 'All Buyers'],
    totalRecipients: 8200,
    stats: {
      sent: 0,
      delivered: 0,
      read: 0,
      clickedOrReplied: 0,
      converted: 0,
      failed: 0,
      revenue: 0,
      cost: 0,
    },
  },
];

export const mockContacts: Contact[] = [
  {
    id: 'cnt_1',
    phone: '+1 (555) 234-5678',
    displayName: 'Elena Rostova',
    optedIn: true,
    optedInAt: '2026-01-15T09:30:00Z',
    optInSource: 'WEBSITE_CHECKOUT',
    rfmSegment: 'CHAMPIONS',
    tags: ['VIP Customers', 'High LTV', 'Fashion Enthusiast'],
    attributes: { city: 'New York', preferredSize: 'M', totalPurchases: 14, lastOrder: 'ORD-8921' },
    lifetimeValue: 2480,
    totalOrders: 14,
    lastActiveAt: new Date(Date.now() - 15 * 60000).toISOString(),
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120',
  },
  {
    id: 'cnt_2',
    phone: '+1 (555) 876-5432',
    displayName: 'Marcus Chen',
    optedIn: true,
    optedInAt: '2026-03-20T11:15:00Z',
    optInSource: 'CLICK_TO_WHATSAPP_AD',
    rfmSegment: 'POTENTIAL_LOYALIST',
    tags: ['Cart Abandoners', 'Tech Buyer'],
    attributes: { city: 'San Francisco', cartTotal: '$320', lastViewed: 'Wireless ANC Headphones' },
    lifetimeValue: 890,
    totalOrders: 3,
    lastActiveAt: new Date(Date.now() - 45 * 60000).toISOString(),
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120',
  },
  {
    id: 'cnt_3',
    phone: '+1 (555) 432-1098',
    displayName: 'Sophia Martinez',
    optedIn: true,
    optedInAt: '2026-05-10T16:00:00Z',
    optInSource: 'QR_CODE',
    rfmSegment: 'LOYAL_CUSTOMERS',
    tags: ['VIP Customers', 'Recent Buyer'],
    attributes: { city: 'Miami', loyaltyTier: 'Gold' },
    lifetimeValue: 1750,
    totalOrders: 9,
    lastActiveAt: new Date(Date.now() - 120 * 60000).toISOString(),
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120',
  },
  {
    id: 'cnt_4',
    phone: '+1 (555) 345-6789',
    displayName: 'David Miller',
    optedIn: false,
    optedInAt: null,
    optInSource: 'ORGANIC_INBOUND',
    rfmSegment: 'NEW_LEADS',
    tags: ['Lead', 'Web Inquiry'],
    attributes: { city: 'Chicago', interest: 'Enterprise Plan' },
    lifetimeValue: 0,
    totalOrders: 0,
    lastActiveAt: new Date(Date.now() - 360 * 60000).toISOString(),
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv_1',
    contact: mockContacts[0],
    windowExpiresAt: new Date(Date.now() + 18 * 3600000).toISOString(), // 18 hrs left in 24h window
    unreadCount: 0,
    assignedAgent: 'Kamlesh Sharma',
    status: 'OPEN',
    sentiment: 'POSITIVE',
    lastMessage: {
      id: 'msg_103',
      conversationId: 'conv_1',
      direction: 'INBOUND',
      status: 'READ',
      content: 'Can you confirm if the silk blazer is available in midnight blue?',
      timestamp: new Date(Date.now() - 12 * 60000).toISOString(),
    },
  },
  {
    id: 'conv_2',
    contact: mockContacts[1],
    windowExpiresAt: new Date(Date.now() + 8 * 3600000).toISOString(), // 8 hrs left
    unreadCount: 1,
    assignedAgent: 'Kamlesh Sharma',
    status: 'OPEN',
    sentiment: 'NEUTRAL',
    lastMessage: {
      id: 'msg_202',
      conversationId: 'conv_2',
      direction: 'INBOUND',
      status: 'DELIVERED',
      content: 'Does the 20% discount code apply to audio accessories as well?',
      timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
    },
  },
  {
    id: 'conv_3',
    contact: mockContacts[2],
    windowExpiresAt: new Date(Date.now() - 2 * 3600000).toISOString(), // Expired 2 hrs ago (Needs Template to start session)
    unreadCount: 0,
    assignedAgent: 'Unassigned',
    status: 'RESOLVED',
    sentiment: 'POSITIVE',
    lastMessage: {
      id: 'msg_302',
      conversationId: 'conv_3',
      direction: 'OUTBOUND',
      status: 'READ',
      content: 'Thank you for shopping with us Sophia! Your order has been delivered.',
      timestamp: new Date(Date.now() - 26 * 3600000).toISOString(),
    },
  },
];

export const mockMessagesByConvId: Record<string, Message[]> = {
  conv_1: [
    {
      id: 'msg_101',
      conversationId: 'conv_1',
      direction: 'OUTBOUND',
      status: 'READ',
      content: '⚡ Exclusive Summer Flash Sale! Hi Elena, your 25% VIP discount is live. Use code VIP25 at checkout.',
      timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
    },
    {
      id: 'msg_101_note',
      conversationId: 'conv_1',
      direction: 'OUTBOUND',
      status: 'READ',
      isInternalNote: true,
      authorName: 'Kamlesh Sharma',
      content: '📌 Note: Elena is a top VIP buyer ($2,480 LTV). Offer express priority dispatch if she places an order today.',
      timestamp: new Date(Date.now() - 3.5 * 3600000).toISOString(),
    },
    {
      id: 'msg_102',
      conversationId: 'conv_1',
      direction: 'INBOUND',
      status: 'READ',
      content: 'Awesome! Looking at the new collection now.',
      timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    },
    {
      id: 'msg_103',
      conversationId: 'conv_1',
      direction: 'INBOUND',
      status: 'READ',
      content: 'Can you confirm if the silk blazer is available in midnight blue?',
      timestamp: new Date(Date.now() - 12 * 60000).toISOString(),
    },
  ],
  conv_2: [
    {
      id: 'msg_201',
      conversationId: 'conv_2',
      direction: 'OUTBOUND',
      status: 'READ',
      content: 'Hi Marcus, you left items in your cart! Complete your checkout for Free Express Shipping.',
      timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    },
    {
      id: 'msg_202',
      conversationId: 'conv_2',
      direction: 'INBOUND',
      status: 'DELIVERED',
      content: 'Does the 20% discount code apply to audio accessories as well?',
      timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
    },
  ],
  conv_3: [
    {
      id: 'msg_301',
      conversationId: 'conv_3',
      direction: 'INBOUND',
      status: 'READ',
      content: 'Package received on time, thank you!',
      timestamp: new Date(Date.now() - 28 * 3600000).toISOString(),
    },
    {
      id: 'msg_302',
      conversationId: 'conv_3',
      direction: 'OUTBOUND',
      status: 'READ',
      content: 'Thank you for shopping with us Sophia! Your order has been delivered.',
      timestamp: new Date(Date.now() - 26 * 3600000).toISOString(),
    },
  ],
};
